import { beforeEach, describe, expect, it, vi } from 'vitest'
import type { ProcessInfo } from '@shared/types-extended'

const storeData: { aliases: unknown[]; autoNameCounters: Record<string, number> } = {
  aliases: [],
  autoNameCounters: {}
}

vi.mock('electron-store', () => ({
  default: class StoreMock {
    get(key: 'aliases' | 'autoNameCounters', defaultValue: unknown) {
      return storeData[key] ?? defaultValue
    }

    set(key: 'aliases' | 'autoNameCounters', value: unknown) {
      if (key === 'aliases') {
        storeData.aliases = Array.isArray(value) ? value : []
        return
      }
      storeData.autoNameCounters = typeof value === 'object' && value !== null
        ? value as Record<string, number>
        : {}
    }
  }
}))

import { AIAliasManager } from './AIAliasManager'

function createClaudeProcess(overrides: Partial<ProcessInfo> = {}): ProcessInfo {
  return {
    pid: 10,
    name: 'claude.exe',
    command: 'C:\\Users\\HP\\AppData\\Roaming\\npm\\node_modules\\@anthropic-ai\\claude-code\\bin\\claude.exe -p --name p4-active-1',
    cpu: 0,
    memory: 128,
    status: 'waiting',
    startTime: Date.now(),
    type: 'ai-tool',
    workingDir: 'C:\\Users\\HP\\AppData\\Roaming\\npm\\node_modules',
    ...overrides
  }
}

describe('AIAliasManager', () => {
  beforeEach(() => {
    storeData.aliases = []
    storeData.autoNameCounters = {}
  })

  it('uses a CLI --name value as the auto alias for named AI sessions', () => {
    const manager = new AIAliasManager()
    const alias = manager.matchOrCreateAlias(undefined, createClaudeProcess(), 'claude-code')

    expect(alias?.alias).toBe('p4-active-1')
    expect(alias?.autoGenerated).toBe(true)
  })



  it('honors a CLI --name value over an existing reliable working directory alias', () => {
    const manager = new AIAliasManager()
    const sharedWorkingDir = String.raw`D:\Desktop\CREATOR ONE\devhub`
    const claudeExe = String.raw`C:\Users\HP\AppData\Roaming\npm\node_modules\@anthropic-ai\claude-code\bin\claude.exe`

    const previous = manager.matchOrCreateAlias(
      undefined,
      createClaudeProcess({
        pid: 21,
        command: `${claudeExe} -p previous workload`,
        workingDir: sharedWorkingDir
      }),
      'claude-code'
    )
    const named = manager.matchOrCreateAlias(
      undefined,
      createClaudeProcess({
        pid: 22,
        command: `${claudeExe} -p --name p4-active-1`,
        workingDir: sharedWorkingDir
      }),
      'claude-code'
    )

    expect(previous?.alias).toBe('Claude Code-1')
    expect(named?.alias).toBe('p4-active-1')
    expect(named?.id).not.toBe(previous?.id)
  })
  it('does not reuse an installed node_modules directory as a stable identity', () => {
    const manager = new AIAliasManager()

    const first = manager.matchOrCreateAlias(
      undefined,
      createClaudeProcess({
        pid: 11,
        command: 'C:\\Users\\HP\\AppData\\Roaming\\npm\\node_modules\\@anthropic-ai\\claude-code\\bin\\claude.exe -p --name p4-idle'
      }),
      'claude-code'
    )
    const second = manager.matchOrCreateAlias(
      undefined,
      createClaudeProcess({
        pid: 12,
        command: 'C:\\Users\\HP\\AppData\\Roaming\\npm\\node_modules\\@anthropic-ai\\claude-code\\bin\\claude.exe -p --name p4-active-1'
      }),
      'claude-code'
    )

    expect(first?.alias).toBe('p4-idle')
    expect(second?.alias).toBe('p4-active-1')
    expect(second?.id).not.toBe(first?.id)
  })
})
