import Store from 'electron-store'
import { createHash } from 'crypto'
import { AIWindowAlias, AIToolType, ProcessInfo, WindowInfo, validateAliasName } from '@shared/types-extended'

interface AIAliasStoreSchema {
  aliases: AIWindowAlias[]
  /** Counter per tool type for auto-naming (e.g., "Claude Code-1", "Claude Code-2") */
  autoNameCounters: Record<string, number>
}

const TOOL_DISPLAY_NAMES: Record<AIToolType, string> = {
  'codex': 'Codex CLI',
  'claude-code': 'Claude Code',
  'gemini-cli': 'Gemini CLI',
  'cursor': 'Cursor',
  'opencode': 'OpenCode',
  'aider': 'Aider',
  'windsurf': 'Windsurf',
  'continue-dev': 'Continue',
  'cline': 'Cline',
  'other': 'AI Tool',
}

export class AIAliasManager {
  private store: Store<AIAliasStoreSchema>
  /** In-memory set of PIDs that already got an auto-name this session */
  private autoNamedPids = new Set<number>()

  constructor() {
    this.store = new Store<AIAliasStoreSchema>({
      name: 'devhub-ai-aliases',
      schema: {
        aliases: {
          type: 'array' as const,
          default: []
        },
        autoNameCounters: {
          type: 'object' as const,
          default: {}
        }
      }
    })
  }

  getAll(): AIWindowAlias[] {
    return this.store.get('aliases', [])
  }

  set(alias: AIWindowAlias): boolean {
    // Validate alias name
    const validation = validateAliasName(alias.alias)
    if (!validation.valid) {
      console.warn(`Invalid alias name: ${validation.error}`)
      return false
    }

    const aliases = this.getAll()
    const index = aliases.findIndex(a => a.id === alias.id)
    if (index >= 0) {
      aliases[index] = alias
    } else {
      aliases.push(alias)
    }
    this.store.set('aliases', aliases)
    return true
  }

  remove(aliasId: string): boolean {
    const aliases = this.getAll()
    const filtered = aliases.filter(a => a.id !== aliasId)
    if (filtered.length === aliases.length) return false
    this.store.set('aliases', filtered)
    return true
  }

  /**
   * Generate an auto-name for an AI window: e.g., "Claude Code-1", "Codex CLI-2"
   * Each tool type has an incrementing counter.
   */
  generateAutoName(toolType: AIToolType): string {
    const counters = this.store.get('autoNameCounters', {})
    const key = toolType
    const current = (counters[key] ?? 0) + 1
    counters[key] = current
    this.store.set('autoNameCounters', counters)
    const displayName = TOOL_DISPLAY_NAMES[toolType] || 'AI Tool'
    return `${displayName}-${current}`
  }

  /**
   * Create or restore an alias for a detected AI process.
   * 1. First try to match an existing alias (by workingDir, command hash, etc.)
   * 2. If no match, auto-generate a new name and persist it.
   */
  matchOrCreateAlias(
    window: WindowInfo | undefined,
    process: ProcessInfo,
    toolType: AIToolType
  ): AIWindowAlias | null {
    // First, try to match existing alias
    const matched = this.matchAlias(window, process, toolType)
    if (matched) return matched

    // Avoid creating duplicate auto-names for the same PID in one session
    if (this.autoNamedPids.has(process.pid)) return null

    // Auto-generate a new alias
    const autoName = this.generateAutoName(toolType)
    const newAlias: AIWindowAlias = {
      id: `auto_${toolType}_${process.pid}_${Date.now()}`,
      alias: autoName,
      matchCriteria: {
        // pid is intentionally NOT persisted: PIDs are recycled across restarts
        // and would cause false matches. Use autoNamedPids set for in-session dedup.
        toolType,
        workingDir: process.workingDir,
        commandHash: hashCommand(process.command),
        titlePrefix: window?.title?.substring(0, 30),
      },
      createdAt: Date.now(),
      lastMatchedAt: Date.now(),
      autoGenerated: true,
    }

    this.set(newAlias)
    this.autoNamedPids.add(process.pid)
    return newAlias
  }

  matchAlias(
    window: WindowInfo | undefined,
    process: ProcessInfo,
    toolType: AIToolType
  ): AIWindowAlias | null {
    const aliases = this.getAll()
    if (aliases.length === 0) return null

    let bestAlias: AIWindowAlias | null = null
    let bestScore = 0

    for (const alias of aliases) {
      let score = 0

      // toolType must match; mismatch means score = 0
      if (alias.matchCriteria.toolType !== toolType) continue

      // PID exact match (most reliable while process alive)
      if (alias.matchCriteria.pid != null && alias.matchCriteria.pid === process.pid) {
        score += 50
      }

      // Working directory match (stable across restart)
      if (
        alias.matchCriteria.workingDir &&
        process.workingDir &&
        alias.matchCriteria.workingDir === process.workingDir
      ) {
        score += 30
      }

      // Command hash match (stable across restart)
      if (
        alias.matchCriteria.commandHash &&
        alias.matchCriteria.commandHash === hashCommand(process.command)
      ) {
        score += 15
      }

      // Executable path match
      if (
        alias.matchCriteria.executablePath &&
        process.command.includes(alias.matchCriteria.executablePath)
      ) {
        score += 10
      }

      // Title prefix match (weakest signal)
      if (
        alias.matchCriteria.titlePrefix &&
        window?.title?.startsWith(alias.matchCriteria.titlePrefix)
      ) {
        score += 5
      }

      if (score > bestScore) {
        bestScore = score
        bestAlias = alias
      }
    }

    // Threshold: at least 30 (workingDir alone is enough)
    return bestScore >= 30 ? bestAlias : null
  }

  updateLastMatched(aliasId: string): void {
    const aliases = this.getAll()
    const alias = aliases.find(a => a.id === aliasId)
    if (alias) {
      alias.lastMatchedAt = Date.now()
      this.store.set('aliases', aliases)
    }
  }

  /** Rename an alias (user-defined name). Also marks it as no longer auto-generated. */
  rename(aliasId: string, newName: string): boolean {
    const validation = validateAliasName(newName)
    if (!validation.valid) return false

    const aliases = this.getAll()
    const alias = aliases.find(a => a.id === aliasId)
    if (!alias) return false

    alias.alias = newName.trim()
    alias.autoGenerated = false
    this.store.set('aliases', aliases)
    return true
  }

  /** Get tool display name */
  static getToolDisplayName(toolType: AIToolType): string {
    return TOOL_DISPLAY_NAMES[toolType] || 'AI Tool'
  }

  /** Clear auto-name tracking for a PID (when process exits) */
  clearAutoNamedPid(pid: number): void {
    this.autoNamedPids.delete(pid)
  }
}

export function hashCommand(command: string): string {
  return createHash('sha256').update(command).digest('hex').slice(0, 16)
}
