import { randomUUID } from 'node:crypto'
import { setTimeout as delay } from 'node:timers/promises'
import PQueue from 'p-queue'
import type { AIWindowAlias, AIToolType, ServiceResult, WindowInfo } from '@shared/types-extended'
import {
  WINDOW_BATCH_LIMITS,
  windowBatchCancelResponseSchema,
  windowBatchProgressSchema,
  windowBatchResultSchema,
  windowBatchStartResponseSchema,
  windowBatchUndoResponseSchema,
  type WindowBatchCancelResponse,
  type WindowBatchProgress,
  type WindowBatchRequest,
  type WindowBatchResult,
  type WindowBatchStartResponse,
  type WindowBatchUndoResponse
} from '@shared/schemas/r8-runtime'
import type { WindowManager } from './WindowManager'
import type { AIAliasManager } from './AIAliasManager'
import { stripAppliedAliasPrefix } from './AIAliasManager'
import { InjectTextService, type InjectTextWindowManager } from './inject/InjectTextService'

export type WindowBatchWindowManager = Pick<
WindowManager,
'focusWindow'
| 'scanWindows'
| 'minimizeWindow'
| 'restoreWindow'
| 'closeWindow'
| 'setWindowTopmost'
| 'screenshotWindow'
| 'setWindowTitle'
| 'sendKeysToWindow'
| 'sendTextToWindow'
> & InjectTextWindowManager & {
  focusWindows?: (hwnds: readonly number[], intervalMs?: number) => Promise<Array<{ hwnd: number; result: ServiceResult }>>
}

type ProgressPublisher = (progress: WindowBatchProgress) => void
type WindowBatchAliasManager = Pick<AIAliasManager, 'getAll' | 'set' | 'remove'>

interface WindowBatchExecutorOptions {
  aliasManager?: WindowBatchAliasManager
  moveToDesktop?: (hwnd: number, desktopId: string) => Promise<ServiceResult<unknown>>
  updateTopmostState?: (hwnd: number, topmost: boolean) => void
}

interface WindowBatchJob {
  jobId: string
  request: WindowBatchRequest
  queue: PQueue
  pendingHwnds: Set<number>
  undoableHwnds: Set<number>
  results: WindowBatchResult[]
  cancelled: boolean
  completed: boolean
  createdAt: number
  completedAt: number | null
  undoDeadlineAt: number | null
  publishTimer: ReturnType<typeof setTimeout> | null
  lastPublishedAt: number
}

interface ServiceResultLike {
  success: boolean
  data?: unknown
  error?: string
}

const AI_TOOL_TYPES = new Set<AIToolType>([
  'codex',
  'claude-code',
  'gemini-cli',
  'cursor',
  'opencode',
  'aider',
  'windsurf',
  'continue-dev',
  'cline',
  'other'
])

export class WindowBatchExecutionError extends Error {
  constructor(readonly code: string, message: string) {
    super(`${code}: ${message}`)
    this.name = 'WindowBatchExecutionError'
  }
}

function isServiceResultLike(value: unknown): value is ServiceResultLike {
  return typeof value === 'object'
    && value !== null
    && 'success' in value
    && typeof (value as { success: unknown }).success === 'boolean'
}

function extractStringArg(args: Record<string, unknown>, keys: readonly string[]): string | null {
  for (const key of keys) {
    const value = args[key]
    if (typeof value === 'string' && value.trim().length > 0) {
      return value.trim()
    }
  }
  return null
}

function extractToolType(args: Record<string, unknown>): AIToolType {
  const value = args.toolType
  return typeof value === 'string' && AI_TOOL_TYPES.has(value as AIToolType) ? value as AIToolType : 'other'
}

function serviceFailure(error: string): ServiceResult {
  return { success: false, error }
}

function findExistingAlias(aliases: readonly AIWindowAlias[], windowInfo: WindowInfo): AIWindowAlias | undefined {
  return aliases.find(alias => alias.appliedExternalTitle?.hwnd === windowInfo.hwnd)
    ?? aliases.find(alias => alias.matchCriteria.pid === windowInfo.pid)
    ?? aliases.find(alias => alias.matchCriteria.titlePrefix && stripAppliedAliasPrefix(windowInfo.title).startsWith(alias.matchCriteria.titlePrefix))
}

function buildBatchAliasRecord(
  previousAlias: AIWindowAlias | undefined,
  windowInfo: WindowInfo,
  aliasName: string,
  appliedTitle: string,
  toolType: AIToolType
): AIWindowAlias {
  const originalTitle = stripAppliedAliasPrefix(windowInfo.title)
  return {
    id: previousAlias?.id ?? `window_alias_${windowInfo.pid}_${windowInfo.hwnd}_${Date.now()}`,
    alias: aliasName,
    matchCriteria: {
      ...previousAlias?.matchCriteria,
      pid: windowInfo.pid,
      titlePrefix: originalTitle.substring(0, 30),
      executablePath: windowInfo.processName,
      toolType
    },
    createdAt: previousAlias?.createdAt ?? Date.now(),
    lastMatchedAt: Date.now(),
    color: previousAlias?.color,
    autoGenerated: false,
    appliedExternalTitle: {
      hwnd: windowInfo.hwnd,
      originalTitle,
      appliedTitle,
      appliedAt: Date.now()
    }
  }
}

export class WindowBatchExecutor {
  private readonly jobs = new Map<string, WindowBatchJob>()
  private readonly injectTextService: InjectTextService

  constructor(
    private readonly windowManager: WindowBatchWindowManager,
    private readonly publish: ProgressPublisher,
    private readonly options: WindowBatchExecutorOptions = {}
  ) {
    this.injectTextService = new InjectTextService(windowManager)
  }

  run(request: WindowBatchRequest): WindowBatchStartResponse {
    this.assertConfirmation(request)

    const jobId = randomUUID()
    const job: WindowBatchJob = {
      jobId,
      request,
      queue: new PQueue({ concurrency: request.action === 'focus' ? 1 : WINDOW_BATCH_LIMITS.PARALLEL }),
      pendingHwnds: new Set(request.hwnds),
      undoableHwnds: new Set(),
      results: [],
      cancelled: false,
      completed: false,
      createdAt: Date.now(),
      completedAt: null,
      undoDeadlineAt: null,
      publishTimer: null,
      lastPublishedAt: 0
    }

    this.jobs.set(jobId, job)
    this.publishProgress(job, 'running', true)

    if (request.action === 'focus' && typeof this.windowManager.focusWindows === 'function') {
      void job.queue.add(() => this.runFocusBatch(job))
    } else {
      for (const hwnd of request.hwnds) {
        void job.queue.add(() => this.runOne(job, hwnd))
      }
    }

    void job.queue.onIdle().then(() => {
      this.completeJob(job)
    })

    return windowBatchStartResponseSchema.parse({ jobId })
  }

  private async runFocusBatch(job: WindowBatchJob): Promise<void> {
    if (job.cancelled) {
      for (const hwnd of [...job.pendingHwnds]) {
        job.pendingHwnds.delete(hwnd)
        this.recordResult(job, windowBatchResultSchema.parse({
          hwnd,
          status: 'skipped',
          error: 'E_CANCELLED: batch job was cancelled'
        }))
      }
      this.publishProgress(job, 'cancelled')
      return
    }

    const focusWindows = this.windowManager.focusWindows
    if (typeof focusWindows !== 'function') return

    try {
      const results = await focusWindows.call(
        this.windowManager,
        job.request.hwnds,
        WINDOW_BATCH_LIMITS.FOCUS_INTERVAL_MS
      )
      for (const item of results) {
        job.pendingHwnds.delete(item.hwnd)
        if (job.results.some(result => result.hwnd === item.hwnd)) continue
        this.recordResult(job, this.toBatchResult(item.hwnd, item.result))
        this.publishProgress(job, job.cancelled ? 'cancelled' : 'running')
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : 'focus batch failed'
      for (const hwnd of [...job.pendingHwnds]) {
        job.pendingHwnds.delete(hwnd)
        if (job.results.some(result => result.hwnd === hwnd)) continue
        this.recordResult(job, windowBatchResultSchema.parse({
          hwnd,
          status: 'failed',
          error: message
        }))
      }
    }

    for (const hwnd of [...job.pendingHwnds]) {
      job.pendingHwnds.delete(hwnd)
      if (job.results.some(result => result.hwnd === hwnd)) continue
      this.recordResult(job, windowBatchResultSchema.parse({
        hwnd,
        status: 'failed',
        error: 'focus batch did not return a result'
      }))
    }

    this.publishProgress(job, job.cancelled ? 'cancelled' : 'running')
  }

  cancel(jobId: string): WindowBatchCancelResponse {
    const job = this.requireJob(jobId)
    if (job.completed) {
      return windowBatchCancelResponseSchema.parse({ jobId, cancelled: false, skipped: 0 })
    }

    job.cancelled = true
    job.queue.clear()
    const pending = [...job.pendingHwnds]
    job.pendingHwnds.clear()
    for (const hwnd of pending) {
      this.recordResult(job, windowBatchResultSchema.parse({
        hwnd,
        status: 'skipped',
        error: 'E_CANCELLED: batch job was cancelled before this HWND started'
      }))
    }
    this.publishProgress(job, 'cancelled', true)
    return windowBatchCancelResponseSchema.parse({ jobId, cancelled: true, skipped: pending.length })
  }

  async undo(jobId: string): Promise<WindowBatchUndoResponse> {
    const job = this.requireJob(jobId)
    if (!job.completed) {
      throw new WindowBatchExecutionError('E_JOB_RUNNING', `Batch job is still running: ${jobId}`)
    }
    if (job.request.action !== 'minimize') {
      return windowBatchUndoResponseSchema.parse({ jobId, undone: 0, results: [] })
    }
    if (job.undoDeadlineAt === null || Date.now() > job.undoDeadlineAt) {
      throw new WindowBatchExecutionError('E_TIMEOUT', `Undo window expired for batch job: ${jobId}`)
    }

    const undoQueue = new PQueue({ concurrency: WINDOW_BATCH_LIMITS.PARALLEL })
    const targets = job.results
      .filter(result => result.status === 'ok' && job.undoableHwnds.has(result.hwnd))
      .map(result => result.hwnd)

    const undoResults: WindowBatchResult[] = []
    await Promise.all(targets.map(hwnd => undoQueue.add(async () => {
      const output = await this.windowManager.restoreWindow(hwnd)
      undoResults.push(this.toBatchResult(hwnd, output, 'rolled-back'))
    })))

    const byHwnd = new Map(undoResults.map(result => [result.hwnd, result]))
    job.results = job.results.map(result => byHwnd.get(result.hwnd) ?? result)
    this.publishProgress(job, 'completed', true)

    return windowBatchUndoResponseSchema.parse({
      jobId,
      undone: undoResults.filter(result => result.status === 'rolled-back').length,
      results: undoResults
    })
  }

  async waitForIdle(jobId: string): Promise<WindowBatchProgress> {
    const job = this.requireJob(jobId)
    await job.queue.onIdle()
    return this.buildProgress(job, job.cancelled ? 'cancelled' : 'completed')
  }

  getProgress(jobId: string): WindowBatchProgress {
    const job = this.requireJob(jobId)
    return this.buildProgress(job, job.cancelled ? 'cancelled' : job.completed ? 'completed' : 'running')
  }

  dispose(): void {
    for (const job of this.jobs.values()) {
      job.queue.clear()
      if (job.publishTimer) {
        clearTimeout(job.publishTimer)
      }
    }
    this.jobs.clear()
  }

  private assertConfirmation(request: WindowBatchRequest): void {
    if (request.confirmed) return
    if (request.action === 'inject-text') {
      throw new WindowBatchExecutionError('E_NEEDS_CONFIRM', 'inject-text requires explicit confirmation')
    }
    if (request.action === 'close' && request.hwnds.length > WINDOW_BATCH_LIMITS.CONFIRM_THRESHOLD_CLOSE) {
      throw new WindowBatchExecutionError('E_NEEDS_CONFIRM', `closing ${request.hwnds.length} windows requires explicit confirmation`)
    }
  }

  private async runOne(job: WindowBatchJob, hwnd: number): Promise<void> {
    job.pendingHwnds.delete(hwnd)
    if (job.cancelled) {
      this.recordResult(job, windowBatchResultSchema.parse({
        hwnd,
        status: 'skipped',
        error: 'E_CANCELLED: batch job was cancelled'
      }))
      this.publishProgress(job, 'cancelled')
      return
    }

    if (job.request.dryRun) {
      this.recordResult(job, windowBatchResultSchema.parse({
        hwnd,
        status: 'skipped',
        output: { dryRun: true, action: job.request.action }
      }))
      this.publishProgress(job, 'running')
      return
    }

    try {
      const output = await this.performWindowAction(job.request, hwnd)
      this.recordResult(job, this.toBatchResult(hwnd, output))
    } catch (error) {
      this.recordResult(job, windowBatchResultSchema.parse({
        hwnd,
        status: 'failed',
        error: error instanceof Error ? error.message : 'unknown error'
      }))
    }
    this.publishProgress(job, job.cancelled ? 'cancelled' : 'running')
  }

  private async performWindowAction(
    request: WindowBatchRequest,
    hwnd: number
  ): Promise<ServiceResult<unknown>> {
    switch (request.action) {
      case 'focus': {
        const result = await this.windowManager.focusWindow(hwnd)
        if (result.success) {
          await delay(WINDOW_BATCH_LIMITS.FOCUS_INTERVAL_MS)
        }
        return result
      }
      case 'minimize':
        return this.windowManager.minimizeWindow(hwnd)
      case 'restore':
        return this.windowManager.restoreWindow(hwnd)
      case 'close':
        return this.windowManager.closeWindow(hwnd)
      case 'aot-toggle':
        return this.performTopmostAction(request, hwnd)
      case 'screenshot':
        return this.windowManager.screenshotWindow(hwnd)
      case 'rename':
        return this.performRenameAction(request, hwnd)
      case 'inject-text':
        return this.performInjectAction(request, hwnd)
      case 'move-to-desktop':
        return this.performMoveToDesktopAction(request, hwnd)
      default:
        return serviceFailure(`E_VALIDATION: unsupported batch action ${String(request.action)}`)
    }
  }

  private async performTopmostAction(request: WindowBatchRequest, hwnd: number): Promise<ServiceResult> {
    const topmost = request.args.topmost
    if (typeof topmost !== 'boolean') {
      return serviceFailure('E_VALIDATION: aot-toggle requires args.topmost boolean; implicit OS state toggle is not available')
    }

    const result = await this.windowManager.setWindowTopmost(hwnd, topmost)
    if (result.success) {
      this.options.updateTopmostState?.(hwnd, topmost)
    }
    return result
  }

  private performRenameAction(request: WindowBatchRequest, hwnd: number): Promise<ServiceResult<unknown>> {
    const aliasName = extractStringArg(request.args, ['alias'])
    const title = extractStringArg(request.args, ['title']) ?? aliasName
    if (!title) {
      return Promise.resolve(serviceFailure('E_VALIDATION: rename requires args.title or args.alias'))
    }
    if (aliasName) {
      return this.performPersistedAliasRename(request, hwnd, aliasName, title)
    }
    return this.windowManager.setWindowTitle(hwnd, title)
  }

  private async performPersistedAliasRename(
    request: WindowBatchRequest,
    hwnd: number,
    aliasName: string,
    title: string
  ): Promise<ServiceResult<unknown>> {
    const aliasManager = this.options.aliasManager
    if (!aliasManager) {
      return serviceFailure('E_ALIAS_MANAGER_UNAVAILABLE: rename args.alias requires the persistent alias manager')
    }

    const scanResult = await this.windowManager.scanWindows(true)
    if (!scanResult.success) {
      return serviceFailure(`E_WINDOW_SCAN_FAILED: ${scanResult.error ?? 'unable to scan windows before alias rename'}`)
    }

    const targetWindow = scanResult.data?.find(windowInfo => windowInfo.hwnd === hwnd)
    if (!targetWindow) {
      return serviceFailure(`E_WINDOW_NOT_FOUND: hwnd ${hwnd} is not present in the latest window scan`)
    }

    const previousAlias = findExistingAlias(aliasManager.getAll(), targetWindow)
    const aliasToSave = buildBatchAliasRecord(
      previousAlias,
      targetWindow,
      aliasName,
      title,
      extractToolType(request.args)
    )

    try {
      if (!aliasManager.set(aliasToSave)) {
        return serviceFailure('E_ALIAS_PERSIST_WRITE_FAILED: alias manager rejected the batch rename payload')
      }
    } catch (error) {
      return serviceFailure(`E_ALIAS_PERSIST_WRITE_FAILED: ${error instanceof Error ? error.message : 'alias persistence failed'}`)
    }

    const titleResult = await this.windowManager.setWindowTitle(hwnd, title)
    if (!titleResult.success) {
      const rolledBack = previousAlias ? aliasManager.set(previousAlias) : aliasManager.remove(aliasToSave.id)
      return serviceFailure(rolledBack
        ? `E_WINDOW_SET_TITLE_FAILED: ${titleResult.error ?? 'failed to apply window title'}`
        : `E_ALIAS_ROLLBACK_FAILED: ${titleResult.error ?? 'failed to apply window title'}`)
    }

    return {
      success: true,
      data: {
        alias: aliasToSave,
        titleApplied: true,
        appliedTitle: title
      }
    }
  }

  private performInjectAction(request: WindowBatchRequest, hwnd: number): Promise<ServiceResult<unknown>> {
    return this.injectTextService.execute({ hwnd, args: request.args, allowSafeKeys: true })
  }

  private performMoveToDesktopAction(request: WindowBatchRequest, hwnd: number): Promise<ServiceResult<unknown>> {
    const desktopId = extractStringArg(request.args, ['desktopId'])
    if (!desktopId) {
      return Promise.resolve(serviceFailure('E_VALIDATION: move-to-desktop requires args.desktopId'))
    }
    if (!this.options.moveToDesktop) {
      return Promise.resolve(serviceFailure('E_VIRTUAL_DESKTOP_UNAVAILABLE: move-to-desktop adapter is not registered'))
    }
    return this.options.moveToDesktop(hwnd, desktopId)
  }

  private toBatchResult(hwnd: number, output: unknown, okStatus: WindowBatchResult['status'] = 'ok'): WindowBatchResult {
    if (isServiceResultLike(output)) {
      if (!output.success) {
        return windowBatchResultSchema.parse({
          hwnd,
          status: 'failed',
          error: output.error ?? 'operation failed',
          output
        })
      }
      return windowBatchResultSchema.parse({
        hwnd,
        status: okStatus,
        output: output.data ?? { success: true }
      })
    }

    return windowBatchResultSchema.parse({ hwnd, status: okStatus, output })
  }

  private recordResult(job: WindowBatchJob, result: WindowBatchResult): void {
    const existingIndex = job.results.findIndex(candidate => candidate.hwnd === result.hwnd)
    if (existingIndex >= 0) {
      job.results[existingIndex] = result
    } else {
      job.results.push(result)
    }
    if (job.request.action === 'minimize' && result.status === 'ok') {
      job.undoableHwnds.add(result.hwnd)
    }
  }

  private completeJob(job: WindowBatchJob): void {
    if (job.completed) return
    job.completed = true
    job.completedAt = Date.now()
    if (job.undoableHwnds.size > 0) {
      job.undoDeadlineAt = job.completedAt + WINDOW_BATCH_LIMITS.UNDO_WINDOW_MS
    }
    this.publishProgress(job, job.cancelled ? 'cancelled' : 'completed', true)
  }

  private publishProgress(job: WindowBatchJob, state: WindowBatchProgress['state'], force = false): void {
    if (job.publishTimer) {
      clearTimeout(job.publishTimer)
      job.publishTimer = null
    }

    const now = Date.now()
    const elapsed = now - job.lastPublishedAt
    if (force || elapsed >= WINDOW_BATCH_LIMITS.PROGRESS_PUSH_INTERVAL_MS) {
      job.lastPublishedAt = now
      this.publish(this.buildProgress(job, state))
      return
    }

    job.publishTimer = setTimeout(() => {
      job.publishTimer = null
      job.lastPublishedAt = Date.now()
      this.publish(this.buildProgress(job, state))
    }, WINDOW_BATCH_LIMITS.PROGRESS_PUSH_INTERVAL_MS - elapsed)
  }

  private buildProgress(job: WindowBatchJob, state: WindowBatchProgress['state']): WindowBatchProgress {
    const failed = job.results.filter(result => result.status === 'failed').length
    return windowBatchProgressSchema.parse({
      jobId: job.jobId,
      total: job.request.hwnds.length,
      completed: job.results.length,
      failed,
      results: job.results,
      state
    })
  }

  private requireJob(jobId: string): WindowBatchJob {
    const job = this.jobs.get(jobId)
    if (!job) {
      throw new WindowBatchExecutionError('E_NOT_FOUND', `Batch job not found: ${jobId}`)
    }
    return job
  }
}
