import type { AIWindowAlias, AIToolType, WindowInfo } from '@shared/types-extended'
import type { ThumbnailWallEntry, ThumbnailWindowGroup } from '@shared/schemas/r8-runtime'
import { thumbnailWindowGroupSchema } from '@shared/schemas/r8-runtime'
import type { AIAliasManager } from './AIAliasManager'
import { stripAppliedAliasPrefix } from './AIAliasManager'

export type ThumbnailAliasManager = Pick<AIAliasManager, 'getAll' | 'set'>

export interface WindowGroupIdentity {
  exe: string
  title: string
  cwd?: string
  alias?: string
  launchOrder?: number
}

export interface WindowGroupResolverOptions {
  aliasManager?: ThumbnailAliasManager
}

function normalizeToken(value: string | undefined): string {
  return value?.trim().toLowerCase() ?? ''
}

export function normalizeWindowTitlePattern(title: string): string {
  return title
    .normalize('NFKC')
    .replace(/\bv?\d+(?:\.\d+){1,}\b/gi, 'vN')
    .replace(/\b\d+\b/g, 'N')
    .replace(/[0-9a-f]{8,}/gi, 'HASH')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase()
}

export function hashWindowGroupIdentity(identity: WindowGroupIdentity): string {
  const payload = [
    normalizeToken(identity.exe),
    normalizeWindowTitlePattern(identity.title),
    normalizeToken(identity.cwd),
    normalizeToken(identity.alias),
    String(identity.launchOrder ?? -1)
  ].join('|')
  let hash = 0x811c9dc5
  for (let index = 0; index < payload.length; index += 1) {
    hash ^= payload.charCodeAt(index)
    hash = Math.imul(hash, 0x01000193) >>> 0
  }
  return hash.toString(16).padStart(8, '0')
}

export function windowGroupKey(identity: WindowGroupIdentity): string {
  return `wg_${hashWindowGroupIdentity(identity)}`
}

export class WindowGroupResolver {
  private readonly aliasManager?: ThumbnailAliasManager

  constructor(options: WindowGroupResolverOptions = {}) {
    this.aliasManager = options.aliasManager
  }

  resolveAlias(windowInfo: WindowInfo): string | null {
    const aliases = this.aliasManager?.getAll() ?? []
    const strippedTitle = stripAppliedAliasPrefix(windowInfo.title)
    const matchedAlias = aliases.find(alias => alias.appliedExternalTitle?.hwnd === windowInfo.hwnd)
      ?? aliases.find(alias => alias.matchCriteria.pid === windowInfo.pid)
      ?? aliases.find(alias => alias.matchCriteria.titlePrefix && strippedTitle.startsWith(alias.matchCriteria.titlePrefix))
    return matchedAlias?.alias ?? null
  }

  resolveFingerprint(windowInfo: WindowInfo, launchOrder?: number): { fingerprintHash: string; alias: string | null; cwd?: string; launchOrder?: number } {
    const alias = this.resolveAlias(windowInfo)
    const fingerprintHash = windowGroupKey({
      exe: windowInfo.processName,
      title: windowInfo.title,
      alias: alias ?? undefined,
      launchOrder
    })
    return { fingerprintHash, alias, launchOrder }
  }

  buildGroups(entries: readonly ThumbnailWallEntry[]): ThumbnailWindowGroup[] {
    const groups = new Map<string, ThumbnailWindowGroup>()
    for (const entry of entries) {
      const id = entry.groupId ?? entry.fingerprintHash
      const existing = groups.get(id)
      if (existing) {
        existing.members.push(entry.hwnd)
        continue
      }
      groups.set(id, thumbnailWindowGroupSchema.parse({
        id,
        exe: entry.exe,
        titlePattern: normalizeWindowTitlePattern(entry.title),
        cwd: entry.cwd,
        alias: entry.alias ?? undefined,
        launchOrder: entry.launchOrder,
        members: [entry.hwnd]
      }))
    }
    return [...groups.values()].sort((left, right) => left.exe.localeCompare(right.exe) || left.id.localeCompare(right.id))
  }

  setAlias(windowInfo: WindowInfo, alias: string, toolType: AIToolType = 'other'): boolean {
    const aliasManager = this.aliasManager
    if (!aliasManager) return false
    const trimmedAlias = alias.trim()
    if (!trimmedAlias) return false
    const aliases = aliasManager.getAll()
    const existingAlias = aliases.find(item => item.appliedExternalTitle?.hwnd === windowInfo.hwnd)
      ?? aliases.find(item => item.matchCriteria.pid === windowInfo.pid)
      ?? aliases.find(item => item.matchCriteria.titlePrefix && windowInfo.title.startsWith(item.matchCriteria.titlePrefix))
    const now = Date.now()
    const record: AIWindowAlias = {
      id: existingAlias?.id ?? `window_alias_${windowInfo.pid}_${windowInfo.hwnd}_${now}`,
      alias: trimmedAlias,
      matchCriteria: {
        pid: windowInfo.pid,
        titlePrefix: windowInfo.title.slice(0, 60),
        toolType
      },
      createdAt: existingAlias?.createdAt ?? now,
      lastMatchedAt: now,
      color: existingAlias?.color,
      autoGenerated: false,
      appliedExternalTitle: existingAlias?.appliedExternalTitle
    }
    return aliasManager.set(record)
  }
}
