import { describe, expect, it } from 'vitest'
import { R8_FEATURE_FLAGS, R8A_FEATURE_FLAGS, R8B_FEATURE_FLAGS, R8C_FEATURE_FLAGS, assertFeatureFlagRegistry, isFeatureEnabled } from './feature-flags'

describe('R8.A feature flag registry', () => {
  it('keeps every flag unique and dependency-resolvable', () => {
    const registry = assertFeatureFlagRegistry()
    const names = registry.map(flag => flag.name)

    expect(new Set(names).size).toBe(names.length)
    expect(R8A_FEATURE_FLAGS).toHaveLength(55)
    expect(R8B_FEATURE_FLAGS).toHaveLength(18)
    expect(R8C_FEATURE_FLAGS).toHaveLength(56)
    expect(R8_FEATURE_FLAGS).toHaveLength(129)
    expect(names).toContain('R8.A.process.card-list-parity')
    expect(names).toContain('R8.A.theme.default-delta')
    expect(names).toContain('R8.A.window.aot')
    expect(names).toContain('R8.A.port.card-improve')
    expect(names).toContain('R8.A.libs.react-scan')
    expect(names).toContain('R8.A.libs.better-queue')
    expect(names).toContain('R8.A.libs.systeminformation')
    expect(names).toContain('R8.A.libs.cytoscape')
    expect(names).toContain('R8.A.libs.cytoscape-dagre')
    expect(names).toContain('R8.A.libs.tabler-icons')
    expect(names).toContain('R8.A.libs.license-checker')
    expect(names).toContain('R8.B.command.palette')
    expect(names).toContain('R8.B.port.security-tier')
    expect(names).toContain('R8.B.port')
    expect(names).toContain('R8.C.zod.sot')
    expect(names).toContain('R8.C.csv')
    expect(names).toContain('R8.C.shim.gemini')
    expect(names).toContain('R8.C.inject.targets.strict-mode')
    expect(names).toContain('R8.C.ocr.interface')
    expect(registry.find(flag => flag.name === 'R8.C.shim.gemini')).toMatchObject({
      defaultEnabled: true,
      dependsOn: ['R8.C.cli.parser'],
      status: 'enabled'
    })
  })

  it('exposes default disabled states and explicit overrides', () => {
    expect(isFeatureEnabled('R8.A.libs.nut-js')).toBe(false)
    expect(isFeatureEnabled('R8.A.libs.react-scan')).toBe(false)
    expect(isFeatureEnabled('R8.A.libs.systeminformation')).toBe(true)
    expect(isFeatureEnabled('R8.C.skill.cloud-sync')).toBe(false)
    expect(isFeatureEnabled('R8.C.ocr.interface')).toBe(false)
    expect(isFeatureEnabled('R8.A.libs.nut-js', { 'R8.A.libs.nut-js': true })).toBe(true)
    expect(isFeatureEnabled('R8.C.ocr.interface', { 'R8.C.ocr.interface': true })).toBe(false)
    expect(isFeatureEnabled('R8.A.window.aot')).toBe(true)
    expect(isFeatureEnabled('R8.B.statusbar.extension')).toBe(true)
    expect(isFeatureEnabled('R8.C.skill.builtin')).toBe(true)
    expect(isFeatureEnabled('R8.C.skill.editor')).toBe(true)
    expect(isFeatureEnabled('R8.C.csv.driver')).toBe(true)
    expect(isFeatureEnabled('R8.C.shim.gemini')).toBe(true)
    expect(isFeatureEnabled('R8.C.task.queue')).toBe(true)
    expect(isFeatureEnabled('R8.C.watchdog.engine')).toBe(true)
    expect(isFeatureEnabled('R8.C.watchdog.engine.strict')).toBe(false)
    expect(isFeatureEnabled('R8.C.watchdog.engine.strict', { 'R8.C.watchdog.engine.strict': true })).toBe(true)
    expect(isFeatureEnabled('R8.C.watchdog.subprocess')).toBe(true)
    expect(isFeatureEnabled('R8.C.watchdog.subprocess.windows-service')).toBe(false)
    expect(isFeatureEnabled('R8.C.watchdog.subprocess.windows-service', { 'R8.C.watchdog.subprocess.windows-service': true })).toBe(true)
    expect(isFeatureEnabled('R8.C.inject.engine')).toBe(true)
    expect(isFeatureEnabled('R8.C.inject.engine.audit-full-content')).toBe(true)
    expect(isFeatureEnabled('R8.C.inject.targets')).toBe(true)
    expect(isFeatureEnabled('R8.C.inject.targets.strict-mode')).toBe(false)
    expect(isFeatureEnabled('R8.C.inject.targets.strict-mode', { 'R8.C.inject.targets.strict-mode': true })).toBe(true)
    expect(isFeatureEnabled('R8.C.dag.orchestrator')).toBe(true)
    expect(isFeatureEnabled('R8.C.dag.editor')).toBe(true)
    expect(isFeatureEnabled('R8.C.topology.global')).toBe(true)
    expect(isFeatureEnabled('R8.C.topology.attached')).toBe(true)
    expect(isFeatureEnabled('R8.C.flow.attached')).toBe(true)
    expect(isFeatureEnabled('R8.C.signal.fusion')).toBe(true)
    expect(isFeatureEnabled('R8.C.recovery.crash')).toBe(true)
    expect(isFeatureEnabled('R8.C.backup.restore')).toBe(true)
    expect(isFeatureEnabled('R8.C.diagnostic.export')).toBe(true)
    expect(isFeatureEnabled('R8.C.permission.ttl')).toBe(true)
    expect(isFeatureEnabled('R8.C.recording.engine')).toBe(true)
    expect(isFeatureEnabled('R8.C.recording.engine.screenshot')).toBe(true)
    expect(isFeatureEnabled('R8.C.recording.engine.fs')).toBe(true)
    expect(isFeatureEnabled('R8.C.recording.engine.git-diff')).toBe(true)
    expect(isFeatureEnabled('R8.C.cli.cursor-copilot', {}, { platform: 'win32' })).toBe(true)
    expect(isFeatureEnabled('R8.C.cli.cursor-copilot', {}, { platform: 'darwin' })).toBe(false)
    expect(isFeatureEnabled('R8.C.cli.cursor-copilot', {}, { platform: 'linux' })).toBe(false)
  })

  it('rejects duplicate flag names', () => {
    const duplicate = [...R8A_FEATURE_FLAGS, R8A_FEATURE_FLAGS[0]]

    expect(() => assertFeatureFlagRegistry(duplicate)).toThrow(/Duplicate feature flag/)
  })
})
